# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Ewald's Cheat Sheet
site_description: Snippets and how-to's
repo_name: ewaldrode/cheatsheet
repo_url: https://github.com/ewaldrode/cheatsheet
edit_uri: edit/main/docs/
docs_dir: ./docs
site_dir: ./site

theme:
  name: material
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  language: en
  include_search_page: true
  search_index_only: true
  features:
    - navigation.instant
    - search.share
    - search.highlight
    - search.suggest
  plugins:
    - search:
        separator: '[\s\-\.]+'
        prebuild_index: python
        lang:
          - en
    - minify:
        minify_html: true
    - roamlinks
  markdown_extensions:
    - admonition
    - codehilite
    - meta
    - attr_list
    - footnotes
    - pymdownx.details
    - pymdownx.emoji
    - pymdownx.highlight
    - pymdownx.magiclink
    - pymdownx.superfences
    - pymdownx.tabbed
    - pymdownx.tasklist
    - toc:
        permalink: true
  extra_css:
    - stylesheets/extra.css